# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

autofetch_sources: true

# require OpenZeppelin Contracts
dependencies:
  - iearn-finance/yearn-vaults@0.3.2
  - OpenZeppelin/openzeppelin-contracts@3.4.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@yearnvaults=iearn-finance/yearn-vaults@0.3.2"

reports:
  exclude_paths:
    - contracts/test/Token.sol
    - contracts/test/TestGuestList.sol
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
